version: '3.8'

# networks:
#     aTunes:
#         external: true

volumes:
    psql_data: {}
    psql_data_backup: {}
    redis_data: {}

services:
    api:
        build:
            context: .
            dockerfile: ./docker/Dockerfile.local
            args:
                - PYTHON_VERSION=tiangolo/uvicorn-gunicorn-fastapi:python3.8-slim
        image: 'atune_image_local'
        command: ['sh', '-c', 'python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn main:app --reload --host 0.0.0.0 --port 8000']
        ports:
            - 8088:8000
            - 5678:5678
        volumes:
            - ./src:/app
        # networks:
        #     - aTunes
        env_file:
            - ./.envs/_api.env
            - ./.envs/_db.env
        depends_on:
            - db

    db:
        image: postgres:15.1-alpine3.17
        # networks:
        #     - aTunes
        env_file:
            - ./.envs/_db.env
        volumes:
            - psql_data:/var/lib/postgresql/data

    # redis:
    #     image: ${REDIS_IMAGE}
    #     # networks:
    #     #     - aTunes
    #     env_file:
    #         - ./.envs/_redis.env
    #     depends_on:
    #         - db
    #     volumes:
    #         - redis_data:/data

    # json:
    #     image: redislabs/rejson:latest

    search:
        image: redislabs/redisearch:2.6.4
        depends_on:
            - db
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
        volumes:
            - redis_data:/data
